# Generated by Django 5.0.2 on 2025-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pain",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("answer_id", models.BigIntegerField(blank=True, null=True)),
                ("category_id", models.BigIntegerField()),
                ("content", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.IntegerField()),
                ("feedback_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "v2_pain",
            },
        ),
        migrations.CreateModel(
            name="PainAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("category_id", models.BigIntegerField(blank=True, null=True)),
                ("article_category_id", models.BigIntegerField()),
                ("has_text_area", models.BooleanField()),
            ],
            options={
                "db_table": "v2_pain_answer",
            },
        ),
        migrations.CreateModel(
            name="PainArea",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=15)),
                ("is_right", models.BooleanField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
            options={
                "db_table": "v2_pain_area",
            },
        ),
        migrations.CreateModel(
            name="PainAreaDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("area_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("value", models.IntegerField()),
                ("pain_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_pain_area_detail",
            },
        ),
        migrations.CreateModel(
            name="PainCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("question_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_pain_category",
            },
        ),
        migrations.CreateModel(
            name="PainFeedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("category_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "v2_pain_feedback",
            },
        ),
        migrations.CreateModel(
            name="PainQuestion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "v2_pain_question",
            },
        ),
    ]
