# Generated by Django 5.0.2 on 2025-06-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PainArea",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("name", models.CharField(max_length=15)),
                ("is_right", models.TextField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
            options={
                "db_table": "v2_pain_area",
            },
        ),
        migrations.CreateModel(
            name="PainCategory",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("name", models.CharField(max_length=50)),
                ("orders", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_pain_category",
            },
        ),
        migrations.CreateModel(
            name="PainQuestion",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "v2_pain_question",
            },
        ),
        migrations.CreateModel(
            name="PainAnswer",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("name", models.CharField(max_length=50)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("has_text_area", models.TextField()),
                (
                    "article_category",
                    models.ForeignKey(
                        db_column="article_category_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.articlecategory",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pain_management.paincategory",
                    ),
                ),
            ],
            options={
                "db_table": "v2_pain_answer",
            },
        ),
        migrations.CreateModel(
            name="Pain",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        db_column="answer_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pain_management.painanswer",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pain_management.paincategory",
                    ),
                ),
            ],
            options={
                "db_table": "v2_pain",
            },
        ),
        migrations.CreateModel(
            name="PainAreaDetail",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("value", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        db_column="area_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pain_management.painarea",
                    ),
                ),
                (
                    "pain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pain_management.pain",
                    ),
                ),
            ],
            options={
                "db_table": "v2_pain_area_detail",
            },
        ),
        migrations.CreateModel(
            name="PainArticle",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                (
                    "article",
                    models.ForeignKey(
                        db_column="article_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.article",
                    ),
                ),
                (
                    "pain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pain_management.pain",
                    ),
                ),
            ],
            options={
                "db_table": "v2_pain_article",
            },
        ),
        migrations.CreateModel(
            name="PainFeedback",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pain_management.paincategory",
                    ),
                ),
            ],
            options={
                "db_table": "v2_pain_feedback",
            },
        ),
        migrations.AddField(
            model_name="pain",
            name="feedback",
            field=models.ForeignKey(
                db_column="feedback_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pain_management.painfeedback",
            ),
        ),
        migrations.AddField(
            model_name="paincategory",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_column="question_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pain_management.painquestion",
            ),
        ),
    ]
