# Generated by Django 5.0.2 on 2025-06-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pain_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="painquestion",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
