# Generated by Django 5.0.2 on 2025-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignInHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("device_name", models.CharField(max_length=255)),
                (
                    "device_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
                ("os", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "sign_in_history",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("email", models.CharField(max_length=255)),
                ("gender", models.IntegerField()),
                ("is_lock", models.BooleanField()),
                ("nickname", models.CharField(max_length=255)),
                ("aws_user_id", models.CharField(max_length=45)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserDelete",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("reason_id", models.SmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "v2_user_delete",
            },
        ),
        migrations.CreateModel(
            name="UserDeleteReason",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("orders", models.IntegerField()),
            ],
            options={
                "db_table": "v2_user_delete_reason",
            },
        ),
    ]
