# Generated by Django 5.0.2 on 2025-06-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignInHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("device_name", models.CharField(max_length=255)),
                (
                    "device_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
                ("os", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "sign_in_history",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("email", models.CharField(max_length=255, unique=True)),
                ("gender", models.IntegerField()),
                ("is_lock", models.TextField()),
                ("nickname", models.CharField(max_length=255)),
                ("aws_user_id", models.CharField(max_length=45)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserDeleteReason",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("orders", models.IntegerField()),
            ],
            options={
                "db_table": "v2_user_delete_reason",
            },
        ),
        migrations.CreateModel(
            name="CustomerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("inquiry", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "v2_customer_inquiry",
            },
        ),
        migrations.CreateModel(
            name="AccessCode",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField()),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_survey_week", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "access_code",
            },
        ),
        migrations.CreateModel(
            name="UserDelete",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.userdeletereason",
                    ),
                ),
            ],
            options={
                "db_table": "v2_user_delete",
            },
        ),
    ]
