# Generated by Django 5.0.2 on 2025-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppIntegrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recent_version", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField()),
                ("min_version", models.CharField(max_length=30)),
                ("android_debug_hash", models.CharField(max_length=255)),
                ("android_release_hash", models.CharField(max_length=255)),
                ("ios_hash", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "v2_app_integrity",
            },
        ),
        migrations.CreateModel(
            name="AppIntegrityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("app_version", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField()),
                ("mode", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "v2_app_integrity_history",
            },
        ),
        migrations.CreateModel(
            name="ClinicalTrialAccess",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "access_key_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "clinical_trial_access",
            },
        ),
        migrations.CreateModel(
            name="CustomAdmin",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=254, unique=True)),
                ("is_active", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "custom_admin",
            },
        ),
    ]
