# Generated by Django 5.0.2 on 2025-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("name", models.CharField(max_length=15)),
                ("type", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_drug",
            },
        ),
        migrations.CreateModel(
            name="DrugDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("drug_id", models.BigIntegerField()),
                ("time", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_drug_detail",
            },
        ),
        migrations.CreateModel(
            name="DrugType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("orders", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_drug_type",
            },
        ),
    ]
