# Generated by Django 5.0.2 on 2025-06-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugType",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField()),
                ("orders", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_drug_type",
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=15)),
                ("type", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "v2_drug",
            },
        ),
        migrations.CreateModel(
            name="DrugDetail",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("time", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="medications.drug",
                    ),
                ),
            ],
            options={
                "db_table": "v2_drug_detail",
            },
        ),
    ]
