# Generated by Django 5.0.2 on 2025-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("orders", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_habit",
            },
        ),
        migrations.CreateModel(
            name="HabitAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("habit_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_habit_answer",
            },
        ),
        migrations.CreateModel(
            name="HabitCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("is_etc", models.BooleanField()),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_habit_category",
            },
        ),
        migrations.CreateModel(
            name="HabitViolation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("answer_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_habit_violation",
            },
        ),
    ]
