# Generated by Django 5.0.2 on 2025-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("explanation", models.CharField(max_length=50)),
                ("is_pain", models.BooleanField()),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "v2_survey",
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("question_id", models.BigIntegerField()),
                ("value", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("week", models.IntegerField()),
            ],
            options={
                "db_table": "v2_survey_answer",
            },
        ),
        migrations.CreateModel(
            name="SurveyPainAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("content", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("week", models.IntegerField()),
            ],
            options={
                "db_table": "v2_survey_pain_answer",
            },
        ),
        migrations.CreateModel(
            name="SurveyPainAreaDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("survey_pain_answer_id", models.BigIntegerField()),
                ("area_id", models.BigIntegerField()),
                ("value", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_survey_pain_area_detail",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type_id", models.BigIntegerField()),
                ("question_category_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("question_category", models.CharField(max_length=255)),
                ("survey_id", models.IntegerField()),
            ],
            options={
                "db_table": "v2_survey_question",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestionCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("survey_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_survey_question_category",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestionType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_survey_question_type",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestionTypeDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_survey_question_type_detail",
            },
        ),
    ]
