# Generated by Django 5.0.2 on 2025-06-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryQuestion",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("enum_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "v2_diary_question",
            },
        ),
        migrations.CreateModel(
            name="DiaryQuestionCategory",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "v2_diary_question_category",
            },
        ),
        migrations.CreateModel(
            name="DiaryQuestionType",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "v2_diary_question_type",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("explanation", models.CharField(max_length=50)),
                ("is_pain", models.IntegerField()),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("type", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "v2_survey",
            },
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "v2_survey_question_type",
            },
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="surveys.diaryquestion",
                    ),
                ),
            ],
            options={
                "db_table": "v2_diary",
            },
        ),
        migrations.AddField(
            model_name="diaryquestion",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="surveys.diaryquestioncategory",
            ),
        ),
        migrations.AddField(
            model_name="diaryquestion",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="surveys.diaryquestiontype",
            ),
        ),
        migrations.CreateModel(
            name="DiaryQuestionTypeDetail",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="surveys.diaryquestiontype",
                    ),
                ),
            ],
            options={
                "db_table": "v2_diary_question_type_detail",
            },
        ),
        migrations.CreateModel(
            name="PainAnswer",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("week", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "v2_survey_pain_answer",
            },
        ),
        migrations.CreateModel(
            name="PainAreaDetail",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "survey_pain_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="surveys.surveypainanswer",
                    ),
                ),
            ],
            options={
                "db_table": "v2_survey_pain_area_detail",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "question_category_name",
                    models.CharField(db_column="question_category", max_length=255),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        db_column="survey_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "v2_survey_question",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("week", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "db_table": "v2_survey_answer",
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "v2_survey_question_category",
            },
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="question_category",
            field=models.ForeignKey(
                db_column="question_category_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="surveys.surveyquestioncategory",
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="surveys.surveyquestiontype",
            ),
        ),
        migrations.CreateModel(
            name="QuestionTypeDetail",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="surveys.surveyquestiontype",
                    ),
                ),
            ],
            options={
                "db_table": "v2_survey_question_type_detail",
            },
        ),
    ]
