# Generated by Django 5.0.2 on 2025-06-04 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pain_management", "0002_painquestion_deleted"),
        ("surveys", "0002_survey_deleted_surveyanswer_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyanswer",
            name="question_id",
        ),
        migrations.RemoveField(
            model_name="surveypainareadetail",
            name="area_id",
        ),
        migrations.RemoveField(
            model_name="surveypainareadetail",
            name="survey_pain_answer_id",
        ),
        migrations.RemoveField(
            model_name="surveyquestion",
            name="question_category_id",
        ),
        migrations.RemoveField(
            model_name="surveyquestion",
            name="survey_id",
        ),
        migrations.RemoveField(
            model_name="surveyquestion",
            name="type_id",
        ),
        migrations.RemoveField(
            model_name="surveyquestioncategory",
            name="survey_id",
        ),
        migrations.RemoveField(
            model_name="surveyquestiontypedetail",
            name="type_id",
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.surveyquestion",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveypainareadetail",
            name="area",
            field=models.ForeignKey(
                db_column="area_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pain_management.painarea",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveypainareadetail",
            name="survey_pain_answer",
            field=models.ForeignKey(
                db_column="survey_pain_answer_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.surveypainanswer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="question_category_name",
            field=models.CharField(
                db_column="question_category", default=1, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="survey",
            field=models.ForeignKey(
                db_column="survey_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.survey",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="type",
            field=models.ForeignKey(
                db_column="type_id",
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.surveyquestiontype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyquestioncategory",
            name="survey",
            field=models.ForeignKey(
                db_column="survey_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.survey",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyquestiontypedetail",
            name="type",
            field=models.ForeignKey(
                db_column="type_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.surveyquestiontype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="question_category",
            field=models.ForeignKey(
                db_column="question_category_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.surveyquestioncategory",
            ),
        ),
    ]
