# Generated by Django 5.0.2 on 2025-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tutorial", models.CharField(blank=True, max_length=200, null=True)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("has_face", models.BooleanField()),
            ],
            options={
                "db_table": "v2_exercise",
            },
        ),
        migrations.CreateModel(
            name="ExerciseHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exercise_id", models.BigIntegerField()),
                ("user_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_face", models.BooleanField()),
            ],
            options={
                "db_table": "v2_exercise_history",
            },
        ),
        migrations.CreateModel(
            name="ExerciseTime",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time_since_midnight", models.IntegerField()),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_exercise_time",
            },
        ),
    ]
