# Generated by Django 5.0.2 on 2025-05-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessCode",
            fields=[
                (
                    "access_code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField()),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_survey_week", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "access_code",
            },
        ),
    ]
