# Generated by Django 5.0.2 on 2025-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("category_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_article",
            },
        ),
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("is_common", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_article_category",
            },
        ),
        migrations.CreateModel(
            name="ArticleDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("article_id", models.BigIntegerField()),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("image", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "v2_article_detail",
            },
        ),
        migrations.CreateModel(
            name="ArticleViewHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("article_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "v2_article_view_history",
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image", models.CharField(max_length=200)),
                ("background_color", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("orders", models.IntegerField()),
                ("route", models.CharField(max_length=20)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("index", models.IntegerField(blank=True, default=-1, null=True)),
                (
                    "background_color_swatch",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "v2_banner",
            },
        ),
        migrations.CreateModel(
            name="EducationVideo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=2000)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_education_video",
            },
        ),
        migrations.CreateModel(
            name="EducationVideoViewHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("video_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_education_video_view_history",
            },
        ),
        migrations.CreateModel(
            name="Meditation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(max_length=100)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "v2_meditation",
            },
        ),
        migrations.CreateModel(
            name="MeditationHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meditation_id", models.BigIntegerField()),
                ("user_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "v2_meditation_history",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "v2_notice",
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "v2_privacy_policy",
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "v2_term",
            },
        ),
    ]
