# Generated by Django 5.0.2 on 2025-06-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("name", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("is_common", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_article_category",
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image", models.CharField(max_length=200)),
                ("background_color", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
                ("orders", models.IntegerField()),
                ("route", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("index", models.IntegerField(blank=True, null=True)),
                (
                    "background_color_swatch",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "v2_banner",
            },
        ),
        migrations.CreateModel(
            name="ConfidentialTerm",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("type", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "v2_confidential_term",
            },
        ),
        migrations.CreateModel(
            name="EducationVideo",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=2000)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "v2_education_video",
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("answer", models.CharField(blank=True, max_length=500, null=True)),
                ("orders", models.IntegerField()),
                ("question", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "v2_faq",
            },
        ),
        migrations.CreateModel(
            name="MedicalDevice",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(blank=True, null=True)),
                ("is_markdown", models.IntegerField()),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("orders", models.IntegerField()),
            ],
            options={
                "db_table": "v2_medical_device",
            },
        ),
        migrations.CreateModel(
            name="Meditation",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(max_length=100)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "v2_meditation",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_notice",
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_privacy_policy",
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "v2_term",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.articlecategory",
                    ),
                ),
            ],
            options={
                "db_table": "v2_article",
            },
        ),
        migrations.CreateModel(
            name="ArticleDetail",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField()),
                ("image", models.CharField(max_length=255)),
                ("orders", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        db_column="article_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.article",
                    ),
                ),
            ],
            options={
                "db_table": "v2_article_detail",
            },
        ),
        migrations.CreateModel(
            name="ArticleViewHistory",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                (
                    "article",
                    models.ForeignKey(
                        db_column="article_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "v2_article_view_history",
            },
        ),
        migrations.CreateModel(
            name="EducationVideoViewHistory",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.educationvideo",
                    ),
                ),
            ],
            options={
                "db_table": "v2_education_video_view_history",
            },
        ),
        migrations.CreateModel(
            name="MeditationHistory",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                (
                    "meditation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.meditation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "v2_meditation_history",
            },
        ),
    ]
