# Generated by Django 5.0.2 on 2025-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.IntegerField()),
                ("type", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "v2_notification",
            },
        ),
        migrations.CreateModel(
            name="NotificationCategory",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("orders", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enum_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "v2_notification_category",
            },
        ),
        migrations.CreateModel(
            name="NotificationExclusion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("category_id", models.SmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "v2_notification_exclusion",
            },
        ),
    ]
